workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest  
      cocoapods: default  
      ios_signing:
        provisioning_profiles:
          - 'mitete_App_Store_Profile_20250105.mobileprovision'  
          - 'ImageNotification_App_Store_Profile.mobileprovision'  
        certificate: '証明書.p12'  
        certificate_password: 'Wada0224'  
    scripts:
      - name: Build IPA  # アプリをビルドしてIPAファイルを生成
        script: |
          xcode-project build-ipa --scheme "Runner" --configuration Release
    artifacts:
      - build/ios/**/*.ipa  # 生成されたIPAファイルをCodemagicのArtifactsセクションに保存
    publishing:
      app_store_connect:  # 自動でApp Store Connectにアップロードする設定
        apple_id: "wadasan224@gmail.com"  # Apple ID
        app_specific_password: "famy-qzeu-gope-tape"  # App-specific password
