workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: 16.0  
      cocoapods: default  
      ios_signing:
        provisioning_profiles:
          - 'mitete_App_Store_Profile_20250108'  
          - 'ImageNotification_App_Store_Profile'  
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner" --export-options-plist "ios/export_options.plist"
    artifacts:
      - build/ios/**/*.ipa  
