workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest  
      cocoapods: default  
      flutter: stable  # Flutterのバージョンを指定
      ios_signing:
        provisioning_profiles:
          mitete.app: mitete_App_Store_Profile_20250107  # プロビジョニングプロファイルの関連付け
          mitete.app.ImageNotification: ImageNotification_App_Store_Profile  
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
      - name: Build IPA
        script: |
          xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme "Runner" --export-options-plist "ios/export_options.plist"
    artifacts:
      - build/ios/**/*.ipa  # 生成されたIPAファイルをCodemagicのArtifactsセクションに保存
