workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest  
      cocoapods: default  
      ios_signing:
        provisioning_profiles:
          - 'mitete_App_Store_Profile_20250105.mobileprovision'  
          - 'ImageNotification_App_Store_Profile.mobileprovision'  
    scripts:
      - name: Build IPA  # アプリをビルドしてIPAファイルを生成
        script: |
          xcode-project build-ipa --scheme "Runner" --configuration Release
    artifacts:
      - build/ios/**/*.ipa  # 生成されたIPAファイルをCodemagicのArtifactsセクションに保存
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_CONNECT_KEY_ID
          issuer_id: $APP_STORE_CONNECT_ISSUER_ID
          private_key: $APP_STORE_CONNECT_PRIVATE_KEY
