workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
      cocoapods: default
      ios_signing:
        provisioning_profiles:
          - 'path/to/your-provisioning-profile.mobileprovision'
        certificate: 'path/to/your-certificate.p12'
        certificate_password: 'your_certificate_password'
    scripts:
      - name: Install dependencies
        script: |
          gem install bundler
          bundle install
      - name: Build the app
        script: |
          xcode-project build-ipa --scheme "YourAppScheme"
    artifacts:
      - build/ios/**/*.ipa
    publishing:
      app_store_connect:
        apple_id: "your_apple_id@example.com"
        app_specific_password: "your_app_specific_password"
